import { Inter } from "next/font/google";
import "./globals.css";
import { ParalaxProviders } from "./providers";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Fist",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <ParalaxProviders>
        <body className={inter.className}>{children}</body>
      </ParalaxProviders>
    </html>
  );
}
